// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCKVO_MvFeaLAcJ1tgUTiKc9Lq-1fYPE',
    appId: '1:227230971738:web:faa5cbb565f9ce386aa563',
    messagingSenderId: '227230971738',
    projectId: 'nawel-app-c6ab7',
    authDomain: 'nawel-app-c6ab7.firebaseapp.com',
    storageBucket: 'nawel-app-c6ab7.firebasestorage.app',
    measurementId: 'G-F9XQD6HWDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Wq2mZ3jurfvwWFKrYCv9JvkRnBBpufA',
    appId: '1:227230971738:android:60dc0d3eaafd4e056aa563',
    messagingSenderId: '227230971738',
    projectId: 'nawel-app-c6ab7',
    storageBucket: 'nawel-app-c6ab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmV3KDgpspfpueINeZgMwn2_afyLN6xk',
    appId: '1:227230971738:ios:5b529d2c0e01bb896aa563',
    messagingSenderId: '227230971738',
    projectId: 'nawel-app-c6ab7',
    storageBucket: 'nawel-app-c6ab7.firebasestorage.app',
    iosBundleId: 'com.example.simpleEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgmV3KDgpspfpueINeZgMwn2_afyLN6xk',
    appId: '1:227230971738:ios:5b529d2c0e01bb896aa563',
    messagingSenderId: '227230971738',
    projectId: 'nawel-app-c6ab7',
    storageBucket: 'nawel-app-c6ab7.firebasestorage.app',
    iosBundleId: 'com.example.simpleEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCKVO_MvFeaLAcJ1tgUTiKc9Lq-1fYPE',
    appId: '1:227230971738:web:d145447c90bbb27c6aa563',
    messagingSenderId: '227230971738',
    projectId: 'nawel-app-c6ab7',
    authDomain: 'nawel-app-c6ab7.firebaseapp.com',
    storageBucket: 'nawel-app-c6ab7.firebasestorage.app',
    measurementId: 'G-6LJTMP0RKX',
  );
}
